### ISSUE TITLE
yaml-cpp needs to be installed

### ISSUE THREAD

**Issue by pinkenburg** [BNLNPPS/tpc-rs#15]
Currently the includes are just installed in the build area. If I include the tpcrs.h in my code:
#include <tpcrs/tpcrs.h>
it results in a fatal compilation error

/cvmfs/sphenix.sdcc.bnl.gov/x8664_sl7/release/release_play/play.3/include/tpcrs/configurator.h:6:27: fatal error: yaml-cpp/yaml.h: No such file or directory
 #include "yaml-cpp/yaml.h"

Installing the yaml-cpp includes solves that (I copied the static lib for good measure, but am not sure if this is needed or if it is linked into the share lib)

**Comment by plexoos** [comment]
Hmm.. The yaml-cpp headers should go into `include/tpcrs/contrib/`. And they do as I just checked.

```
$cmake -DCMAKE_INSTALL_PREFIX=<path>
$make
$make install
...
$ls <CMAKE_INSTALL_PREFIX>/include/tpcrs/contrib/
yaml-cpp
```

Perhaps, you expected them in `include/` or `include/tpcrs` and did not added `include/tpcrs/contrib/` to the search path

**Comment by plexoos** [comment]
I am going to check if these headers are really required...

**Comment by pinkenburg** [comment]
Just to illustrate the point, create a stupid little test:

#include <tpcrs/tpcrs.h>
int main()
{
  return 0;
}

compiling using my installation under /phenix/scratch/pinkenbu/tpcrs-inst:

[pinkenbu@rcas2601 build]$ g++ -std=c++11 bla.cc -I/phenix/scratch/pinkenbu/tpcrs-inst/include
In file included from /phenix/scratch/pinkenbu/tpcrs-inst/include/tpcrs/tpcrs_core.h:9:0,
                 from /phenix/scratch/pinkenbu/tpcrs-inst/include/tpcrs/tpcrs.h:3,
                 from bla.cc:1:
/phenix/scratch/pinkenbu/tpcrs-inst/include/tpcrs/configurator.h:6:27: fatal error: yaml-cpp/yaml.h: No such file or directory
 #include "yaml-cpp/yaml.h"

Adding the contrib include path in addition fixes this:
g++ -std=c++11 bla.cc -I/phenix/scratch/pinkenbu/tpcrs-inst/include -I/phenix/scratch/pinkenbu/tpcrs-inst/include/tpcrs/contrib
but I don't think adding some path to all makefiles is a good approach.
